### ISSUE TITLE
Problem with (iop|ee)-as preprocessing on OS X

### ISSUE THREAD

**Issue by Darkshadow2** [ps2dev/ps2toolchain#28]
I've run into a problem while compiling the SDK on macOS 10.12.3. It seems that `iop-as` and `ee-as` (and probably `dvp-as` though I haven't run into it) will not do any preprocessing when given a *.S file. When I get to building ps2sdk, I get this:

```
make[2]: Entering directory '/usr/local/ps2dev/build/ps2sdk/iop/debug'
make -C iopdebug
make[3]: Entering directory '/usr/local/ps2dev/build/ps2sdk/iop/debug/iopdebug'
mkdir -p obj/
mkdir -p irx/
iop-gcc -D_IOP -fno-builtin -O2 -G0 -Wall  -I/usr/local/ps2dev/build/ps2sdk/iop/kernel/include -I/usr/local/ps2dev/build/ps2sdk/common/include -Iinclude/  -c src/main.c -o obj/main.o
iop-gcc -D_IOP -fno-builtin -O2 -G0 -Wall  -I/usr/local/ps2dev/build/ps2sdk/iop/kernel/include -I/usr/local/ps2dev/build/ps2sdk/common/include -Iinclude/  -c src/iop_debug.c -o obj/iop_debug.o
iop-as -march=r3000 -EL -G0  src/iop_exceptions.S -o obj/iop_exceptions.o
src/iop_exceptions.S: Assembler messages:
src/iop_exceptions.S:48: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:60: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:64: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:66: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:68: Error: illegal operands `mfhi'
src/iop_exceptions.S:69: Error: illegal operands `mflo'
src/iop_exceptions.S:70: Error: unrecognized opcode `nop// necessary??'
src/iop_exceptions.S:73: Error: unrecognized opcode `nop// necessary??'
src/iop_exceptions.S:75: Error: illegal operands `mfc0 $t0,$3//IOP_COP0_BPC'
src/iop_exceptions.S:76: Error: illegal operands `mfc0 $t1,$5//IOP_COP0_BDA'
src/iop_exceptions.S:77: Error: illegal operands `mfc0 $t2,$8//IOP_COP0_BADVADDR'
src/iop_exceptions.S:78: Error: illegal operands `mfc0 $t3,$9//IOP_COP0_BDAM'
src/iop_exceptions.S:79: Error: illegal operands `mfc0 $t4,$11//IOP_COP0_BPCM'
src/iop_exceptions.S:80: Error: illegal operands `mfc0 $t5,$12//SR'
src/iop_exceptions.S:81: Error: illegal operands `mfc0 $t6,$13//Cause'
src/iop_exceptions.S:82: Error: illegal operands `mfc0 $t7,$14//EPC'
src/iop_exceptions.S:86: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:101: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:113: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:125: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:129: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:131: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:135: Error: illegal operands `mthi'
src/iop_exceptions.S:136: Error: illegal operands `mtlo'
src/iop_exceptions.S:142: Error: illegal operands `mtc0 $t0,$3//IOP_COP0_BPC'
src/iop_exceptions.S:143: Error: illegal operands `mtc0 $t1,$5//IOP_COP0_BDA'
src/iop_exceptions.S:145: Warning: rest of line ignored; first ignored character is `/'
src/iop_exceptions.S:148: Error: illegal operands `mtc0 $t2,$8//IOP_COP0_BADVADDR'
src/iop_exceptions.S:149: Error: illegal operands `mtc0 $t3,$9//IOP_COP0_BDAM'
src/iop_exceptions.S:153: Error: illegal operands `mtc0 $t4,$11//IOP_COP0_BPCM'
src/iop_exceptions.S:154: Error: illegal operands `mtc0 $t5,$12//SR'
src/iop_exceptions.S:158: Error: illegal operands `mtc0 $t6,$13//Cause'
src/iop_exceptions.S:159: Error: illegal operands `mtc0 $t7,$14//EPC'
src/iop_exceptions.S:205: Error: illegal operands `sw'
src/iop_exceptions.S:206: Error: illegal operands `sw'
src/iop_exceptions.S:207: Error: illegal operands `mfc0 $s0,IOP_COP0_DCIC'
src/iop_exceptions.S:208: Error: illegal operands `sw'
src/iop_exceptions.S:209: Error: illegal operands `lw'
src/iop_exceptions.S:210: Error: illegal operands `sw'
src/iop_exceptions.S:211: Error: illegal operands `sw'
src/iop_exceptions.S:212: Error: illegal operands `lw'
src/iop_exceptions.S:213: Error: expression too complex
src/iop_exceptions.S:218: Error: illegal operands `lw'
src/iop_exceptions.S:219: Error: illegal operands `lw'
src/iop_exceptions.S:220: Error: illegal operands `lw'
src/iop_exceptions.S:222: Error: illegal operands `lw'
src/iop_exceptions.S:224: Error: illegal operands `mtc0 $k1,IOP_COP0_DCIC'
src/iop_exceptions.S:229: Error: illegal operands `mtc0 $k1,$14//EPC'
src/iop_exceptions.S:230: Error: illegal operands `lw'
src/iop_exceptions.S:255: Error: illegal operands `sw'
src/iop_exceptions.S:256: Error: illegal operands `sw'
src/iop_exceptions.S:257: Error: illegal operands `sw'
src/iop_exceptions.S:258: Error: illegal operands `lw'
src/iop_exceptions.S:259: Error: illegal operands `lw'
src/iop_exceptions.S:260: Error: illegal operands `sw'
src/iop_exceptions.S:261: Error: illegal operands `sw'
src/iop_exceptions.S:262: Error: expression too complex
src/iop_exceptions.S:267: Error: illegal operands `lw'
src/iop_exceptions.S:268: Error: illegal operands `lw'
src/iop_exceptions.S:269: Error: illegal operands `lw'
src/iop_exceptions.S:271: Error: illegal operands `lw'
src/iop_exceptions.S:273: Error: illegal operands `mtc0 $k1,IOP_COP0_DCIC'
src/iop_exceptions.S:278: Error: illegal operands `mtc0 $k1,$14//EPC'
src/iop_exceptions.S:279: Error: illegal operands `lw'
make[3]: *** [/usr/local/ps2dev/build/ps2sdk/iop/Rules.make:53: obj/iop_exceptions.o] Error 1
make[3]: Leaving directory '/usr/local/ps2dev/build/ps2sdk/iop/debug/iopdebug'
make[2]: *** [/usr/local/ps2dev/build/ps2sdk/Rules.make:21: all-iopdebug] Error 2
make[2]: Leaving directory '/usr/local/ps2dev/build/ps2sdk/iop/debug'
make[1]: *** [/usr/local/ps2dev/build/ps2sdk/Rules.make:21: all-debug] Error 2
make[1]: Leaving directory '/usr/local/ps2dev/build/ps2sdk/iop'
make: *** [makefile:31: all-iop] Error 2
```

I can work around this by manually running the preprocessor to output a *.s file (in this case, running `mv src/iop_exceptions.S src/iop_exceptions.S.S; iop-gcc -E -o src/iop_exceptions.S src/iop_exceptions.S.S`). This is a pain, since I have to build until it errors out, then manually run the preprocessor with the correct include flags and then re-run `make` ... and wait for the next error. Note that the build does complete successfully after doing this (and works), but I'd rather not have to do this.

I'm not sure what the problem is. Binutils builds without any errors, though it has about a billion warnings. Here's the output from doing `./toolchain.sh 001` (compressed because the log is 2.7 MB) (I also edited the build script to use only 1 processor - no other changes made)

[binutils-2.14.log.gz](https://github.com/ps2dev/ps2toolchain/files/751702/binutils-2.14.log.gz)
(oops, the extension should be .tar.gz - my fault. Not re-upping just to correct the file extension)

Let me know if there's anything else that I can provide to help resolve this issue.

**Comment by sp193** [comment]
But *.S files should not be processed directly by any version of AS! Somehow, the Makefile rules do not seem to be working correctly on your computer.

 Everything still works on Debian 8.0, so it may have something to do with differences in platforms. :/
I have never used a Macintosh before, so I cannot really help you with that.

As our tools are very old, they do not compile warning-free, unfortunately.

Sent from my Sony Xperia™ smartphone

**Comment by Darkshadow2** [comment]
Ha, of course, `ee-as` and `iop-as` aren't being called directly anywhere, so that's not the problem. <smacks self on head>

Your comment about differences in platforms had me do little more testing. It seems that everything works fine if I create a case-sensitive volume and build from there.  Mac OS file systems are (unless specifically created otherwise) case-insensitive but case-preserving. I'm not entirely sure why this is a problem though - previous versions of the toolchain didn't have a problem with it.

Guess the issue can be closed. I can just create a case-sensitive disk image to do my compiling and everything should be fine.

**Comment by sp193** [comment]
@uyjulian, do you have any comments on this? Sorry, but you are the only other OSX user that I know of.

Sent from my Sony Xperia™ smartphone

**Comment by uyjulian** [comment]
I don't have macOS 10.12.3, only OSX 10.11.6.
My filesystem is not case-sensitive, and building works for me.
Are you using the new/beta APFS?

**Comment by Darkshadow2** [comment]
No, still with crusty 'ole HFS+. As far as I know, you can only use APFS on a disk image but I could be wrong about that.

I can't think of anything that may affect the build. I do have a custom clang installed, but all the build scripts specifically use /usr/bin/gcc. Hmm, I have Xcode 8.2 that could be a difference. Though really, once the toolchain is built, I couldn't see that being an issue.

Really, once I put everything on a case sensitive file system, it just works. Built the toolchain & SDK, built some other things against it, all works. If I try it on my normal volume, it won't preprocess the files as above. I was definitely surprised by this, as I said I had built & used a previous version of the toolchain and that worked fine.

I could rebuild the toolchain completely and post the log here if you're interested.

**Comment by sp193** [comment]
What do you exactly mean by a "previous version" of the toolchain? The ps2toolchain project builds and installs Binutils, GCC, Newlib, the PS2SDK and ps2client. So if you meant that you used to have no problems (before upgrading), then we cannot possibly say for certain that it is an issue with the toolchain itself (since the PS2SDK is also being updated separately).

Unless, you meant that if you checked out an earlier revision of ps2toolchain today, it will work perfectly fine?

Based on the partial log that you showed previously, iop-as was used to assemble the iop_exception.S file. That should not happen, so it doesn't seem possible for it to be an issue with ps2toolchain because the Makefiles are from ps2sdk.

Sent from my Sony Xperia™ smartphone

**Comment by uyjulian** [comment]
Try deleting `build/ps2sdk` and running `sh ./toolchain.sh 5`. Something might have went wrong, so make used this rule: https://github.com/ps2dev/ps2sdk/blob/master/iop/Rules.make#L52 instead of https://github.com/ps2dev/ps2sdk/blob/master/iop/Rules.make#L49

Also, what is the output of `make --version`?

**Comment by Darkshadow2** [comment]
@sp193 I mean an older build of it. Last time I was using the toolchain (and SDK, etc) was in late 2015 (I think). The version of gcc that was being used was 3.2.2, and is now 3.2.3. That's all I mean by previous version. I've simply been updating everything. And yes, the Makefiles are from ps2sdk, but I was thinking it was a problem with `iop-as` or `iop-gcc`, which would make it an issue with the toolchain.

@uyjulian I don't think it's a problem with the wrong rule being used, as you can see in the log it's trying to use `iop-as` on `src/iop_exceptions.S` (note the capital S).

I think it may be more that iop-gcc, when preprocessing, is trying to write a temp file with the same name in the same place, with the difference being the case. In the case above, trying to write iop_exceptions.s in the same directory iop_exceptions.S is. Which isn't going to work on a case insensitive file system. I don't know for sure this is what's happening, though, it's just a guess. It's the only thing that makes sense in this case, though. Although the *.S file being passed to as makes me doubt that a bit.

I seriously just moved the ps2toolchain folder from my main drive to a case insensitive disk image I made, and it compiled fine. No problems, no errors. Move it back to my main drive, and I get the above error again.  ¯\_(ツ)_/¯

make is:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

(standard make on 10.2.3)

**Comment by sp193** [comment]
I have to agree with uyjulian that it seems to be a problem with either the Makefiles or with Make itself. It is the Makefile rules that determine whether iop-as or iop-gcc should be used. iop-gcc may invoke iop-as internally, but you wouldn't see iop-as get invoked from the terminal.

Linux uses a case-sensitive filesystem by default, so we know that it should not be an issue.

Sent from my Sony Xperia™ smartphone

**Comment by Darkshadow2** [comment]
Well, that seems to be the point. Mac OS X uses a case _in_sensitive filesystem by default. Building there causes errors (for me). Moving everything to a case sensitive filesystem has it all working. Everything else is the same, that's the only thing I'm changing.

**Comment by uyjulian** [comment]
I have the same output of `make --version`.

Change directory to `build/ps2sdk/iop/debug/iopdebug/src`. What is the output of `ls *.S`?

**Comment by Darkshadow2** [comment]
What it should be:
```
exports.tab  imports.lst  iop_dbg_low.S  iop_debug.c  iop_exceptions.S  iopdebug_defs.h  iopdebug_priv.h  irx_imports.h  main.c
```

(This is on the case sensitive disk image I made, though. If you want me to test it on my main drive, let me know and give me a few minutes to get it compiling.)

**Comment by uyjulian** [comment]
You should test it on your main drive

**Comment by Darkshadow2** [comment]
The same... but I'm a bit blown away here. Build just completed fine on my main drive, where it wouldn't before.  This is ... odd..

Give me a few more minutes. I'm going to move over /usr/local/ps2dev and build completely from scratch again (have fast machine, won't take long). I'm wondering if the toolchain is building different between having been built on the case sensitive vs case insensitive filesystem.

**Comment by Darkshadow2** [comment]
Well, seems I wasted everyone's time. My apologies. It's all building fine now. I have _absolutely_ no idea why I was getting errors before. Possibly because I just updated over my old ps2dev stuff and something wasn't cleared out correctly. Though that doesn't entirely explain why it worked when I did the same from a case sensitive filesystem.

Thanks, @sp193 & @uyjulian for helping out with this, and again apologies for it not actually being a problem.

**Comment by sp193** [comment]
Nah, that sometimes happens. It reminds me of when I first started. Back then, I was doing development on Windows and sometimes weird things happened (I guess, mainly due to a lack of experience).

Have a nice day!

Sent from my Sony Xperia™ smartphone
