### ISSUE TITLE
Issue compiling with OSX Sierra/High Sierra

### ISSUE THREAD

**Issue by fjtrujy** [ps2dev/ps2toolchain#32]
Hello,

First of all, I say sorry if this question is stupid but I have been trying to solve it myself but there is no way, so for that reason I'm asking you, `the Masters` of the `PS2DEV`.

I have been days trying to compile the `ps2toolchain` with my MacOS, but I'm stuck on this error:

```
gcc -DIN_GCC -DCROSS_COMPILE   -g -O2 -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wtraditional -pedantic -Wno-long-long  -DHAVE_CONFIG_H  -o cc1plus \
	      cp/call.o cp/decl.o cp/expr.o cp/pt.o cp/typeck2.o cp/class.o cp/decl2.o cp/error.o cp/lex.o cp/parse.o cp/ptree.o cp/rtti.o cp/spew.o cp/typeck.o cp/cvt.o cp/except.o cp/friend.o cp/init.o cp/method.o cp/search.o cp/semantics.o cp/tree.o cp/repo.o cp/dump.o cp/optimize.o cp/mangle.o cp/cp-lang.o attribs.o c-common.o c-format.o c-pragma.o c-semantics.o c-lex.o  main.o libbackend.a libcpp.a ./intl/libintl.a  -liconv  ../libiberty/libiberty.a
Undefined symbols for architecture x86_64:
  "_libc_name_p", referenced from:
      _nothrow_libfn_p in except.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cc1plus] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all-gcc] Error 2
../scripts/004-gcc-3.2.3-stage2.sh: Failed.
```

I have been looking through internet and I have seen people with similar issues, but none of the solutions that they proposed worked to me.

Here you are more information about my current configuration

For instance in that case, I'm trying with 

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036
```

`gcc -v` returns:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

`make -v` returns:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

`patch -v` returns:
```
patch 2.5.8
Copyright (C) 1988 Larry Wall
Copyright (C) 2002 Free Software Foundation, Inc.

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

written by Larry Wall and Paul Eggert
```

I have tried with `Sierra` and `High Sierra`, with `Case Sensitive` disk and `Case Insensitive` disk and it is always failing in the same step.

Here you are the whole output.
[output.log](https://github.com/ps2dev/ps2toolchain/files/1457460/output.log)

Wishing your quick response,
Thanks in advance.

**Comment by ildar** [comment]
I'm story I'm episodical about ps2dev so my advice may be very stupid:
Seems that linker isn't happy with Mac Os's libc. I'm not sure that ps2dev
builds on MacOs at all.
But if you're sure you want to go on (instead of getting Linux in a VM) I'd
suggest you to get GNU environment, firstly glibc.

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by fjtrujy** [comment]
Hello @ildar ,

Thanks for your reply.

It was so useful.

Basically I have followed these instructions:

http://hpc.sourceforge.net/

More concrete:

```
Compiled using source code from the GNU servers. This contains current versions (7.1 is the stable release) of gfortran (free, open source, GNU Fortran 95 compiler), gcc (GNU C) and g++ (GNU C++) compilers that can perform auto-vectorization (i.e. modify code to take advantage of AltiVec/SSE, automatically) and other sophisticated optimizations like OpenMP. For more information, see this webpage. Download my binaries, and cd to the download folder. Then gunzip gcc-7.1-bin.tar.gz (if your browser didn't do so already) and then sudo tar -xvf gcc-7.1-bin.tar -C /. It installs everything in /usr/local. You can invoke the Fortran 95 compiler by simply typing gfortran. You will also need to have Apple's XCode Tools installed from the Mac App Store. With XCode 4 or better you will need to download the command-line tools as an additional step. You will find the option to download the command-line tools in XCode's Preferences. On 10.9 Mavericks or higher, you can get the command-line tools by simply typing xcode-select --install.
```
And the file URL is: `http://prdownloads.sourceforge.net/hpc/gcc-7.1-bin.tar.gz?download`

I think that it could be a very good idea to include that info in the `Readme` of the repo.

What do you think?

Thanks again

**Comment by sp193** [comment]
I'm pretty sure @uyjulian has done it for himself. I know he works from a Mac of some sort.

I have this feeling that it may be solvable. Have you tried [this](https://stackoverflow.com/questions/3040801/error-compiling-gcc-undefined-reference-to-libc-name-p)?

**Comment by uyjulian** [comment]
I did some patch in `cp/except.c`; I don't remember exactly what I did (inline -> static?)

**Comment by fjtrujy** [comment]
> I have this feeling that it may be solvable. Have you tried this?

Yes I tried, in that case the file has content `./gcc/cp/cfns.h`, so is not exactly the same issue that the stackoverflow link says.

Anyway if @uyjulian has a fix would be the best. I prefer to work directly with OS X rather than use a VM with Linux.

Thanks in advance and wishing your response,
Francisco Javier

**Comment by Darkshadow2** [comment]
I know this is old, but the fix *is* in `gcc/cp/cfns.h`. Basically, on macOS it seems `inline` gets (in this case) promoted to a regular function. Changing inline to static probably works (I haven't tried that). I just changed it to `__inline__ __attribute__((__always_inline__))` and that works.

**Comment by uyjulian** [comment]
I'm not sure if I sent the fix or not. If I didn't, I'll send it later today (or this week).
