### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by lptech1024** [ps2dev/ps2toolchain#34]
What is this project licensed as?

Could this information be added to a LICENSE file and referenced in the README?

**Comment by sp193** [comment]
Personally, I do not really know. The tools should be under GPL, while the PS2SDK itself appears to be under AFL.

@ooPo, do you have any idea, since you contributed the original scripts?

**Comment by ooPo** [comment]
Hi! When I started this project I had this text in the toolchain.sh header:

"# Copy all you want. Please give me some credit."
(https://github.com/ps2dev/ps2toolchain/commit/16a47184b3a5fdf4aea45fcc8fee082d3c4d4183#diff-4aa568593ff3ba93745074d6762bc61a)

Somewhere along the way that got lost. I'm open to suggestions, probably either AFL to match PS2SDK or GPL2? I haven't been active in this project in a long time so maybe someone who has can chime in? I'd be willing to go along with whatever they feel is best.

**Comment by ijacquez** [comment]
If all you'd like is to be credited, then MIT or BSD 2-clause would suffice.

**Comment by ooPo** [comment]
There's a pull request available: https://github.com/ps2dev/ps2toolchain/pull/51
