### ISSUE TITLE
texinfo and binutils

### ISSUE THREAD

**Issue by JoKiv** [ps2dev/ps2toolchain#4]
../../../gas/doc/as.texinfo:3628: @itemx must follow @item 
../../../gas/doc/as.texinfo:3630: @itemx must follow @item 
../../../gas/doc/as.texinfo:3632: @itemx must follow @item

Until this issue is fixed the binutils will compile with modification to scripts/001-binutils-2.14.sh

 ## Compile and install.
make clean && make -j 2 MAKEINFO=true && make install MAKEINFO=true && make clean || { exit 1; }

This leaves you without binutils documentation.

**Comment by RafaelBaugis** [comment]
I see same error, and i only can compile binutils with editing install script.
