### ISSUE TITLE
Zlib compilation fails

### ISSUE THREAD

**Issue by AKuHAK** [ps2dev/ps2toolchain#43]
With latest updates My build bot fail at zlib compilation:
[LOG](https://travis-ci.org/AKuHAK/test_build/builds/420815754)
`In file included from gzguts.h:21,
                 from zutil.c:10:
/ps2dev/ps2sdk/ee/include/stdio.h:27: warning: redefinition of `off_t'
/ps2dev/ee/ee/sys-include/sys/types.h:131: warning: `off_t' previously declared here
ee-ar cru libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
ee-gcc -D_EE -O2 -G0 -Wall  -I/ps2dev/ps2sdk/ee/include -I/ps2dev/ps2sdk/common/include -I. -I. -c test/example.c -o test/example.o
In file included from test/example.c:9:
/ps2dev/ps2sdk/ee/include/stdio.h:27: warning: redefinition of `off_t'
/ps2dev/ee/ee/sys-include/sys/types.h:131: warning: `off_t' previously declared here
ee-gcc -mno-crt0 -T/ps2dev/ps2sdk/ee/startup/linkfile -I. \
		-o example.elf /ps2dev/ps2sdk/ee/startup/crt0.o test/example.o -L/ps2dev/ps2sdk/ee/lib libz.a -lc -lkernel
/ps2dev/ee/lib/gcc-lib/ee/3.2.3/../../../../ee/bin/ld: cannot find -lps2sdkc
collect2: ld returned 1 exit status`

**Comment by sp193** [comment]
As of commit 48ba575, there is a need to do additional steps:
- ln -sf "$PS2SDK/ee/lib/libc.a"      "$PS2DEV/ee/ee/lib/libps2sdkc.a" || { exit 1; }
- ln -sf "$PS2SDK/ee/lib/libkernel.a" "$PS2DEV/ee/ee/lib/libkernel.a" || { exit 1; }

This is also done by the [PS2SDK setup script](https://github.com/ps2dev/ps2toolchain/blob/master/scripts/005-ps2sdk.sh#L35).

But now that you have brought up this issue, I want to also remark that the same errors are visible during GCC stage 2 compilation. This would negatively affect some steps, like when configure checks whether there is any tool installed for parsing the output for nm. However, nothing bad seems to be happening so far.

@rickgaiser, FYI.

**Comment by AKuHAK** [comment]
Oh thank you - I really missed that step somehow.

**Comment by rickgaiser** [comment]
@sp193 What errors are visible during GCC stage 2 compilation? Is this also related to the mentioned commit?

Perhaps it's better to move the creation of the symbolic links to the ps2sdk "make install" target?

**Comment by sp193** [comment]
I mean, we can find messages like this one, around the config.log files for GCC and its libraries:
```
configure:3164: checking for working strncmp
configure:3236: /home/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/gcc/xgcc -B/home/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/gcc/ -nostdinc -B/home/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/newlib/ -isystem /home/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/newlib/targ-include -isystem /home/ps2toolchain/build/gcc-3.2.3/newlib/libc/include -B/usr/local/ps2dev/ee/ee/bin/ -B/usr/local/ps2dev/ee/ee/lib/ -isystem /usr/local/ps2dev/ee/ee/include -o conftest -O2 -g -O2   conftest.c  1>&5
C:\MinGW\msys\1.0\local\ps2dev\ee\ee\bin\ld.exe: cannot find -lps2sdkc
configure: failed program was:
```
But as you already know, GCC stage 2still seems to build fine. So it could be just a cosmetic thing.

> Perhaps it's better to move the creation of the symbolic links to the ps2sdk "make install" target?
It's a one-time affair though. But if it is better, then I don't see why not.
