### ISSUE TITLE
multicore script failed on WSL

### ISSUE THREAD

**Issue by AKuHAK** [ps2dev/ps2toolchain#48]
This is probably related to multicore - patch nr 004 failed due to multicore not functioning properly. Windows 10, Ubuntu app from Windoows Store

`xgcc: cannot specify -o with -c or -S and multiple compilations
Makefile:407: recipe for target 'globals.lo' failed
make[3]: *** [globals.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/gcc/xgcc -shared-libgcc -B/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/gcc/ -nostdinc++ -L/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3/src -L/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3/src/.libs -nostdinc -B/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/newlib/ -isystem /root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/newlib/targ-include -isystem /root/ps2toolchain/build/gcc-3.2.3/newlib/libc/include -B/usr/local/ps2dev/ee/ee/bin/ -B/usr/local/ps2dev/ee/ee/lib/ -isystem /usr/local/ps2dev/ee/ee/include -nostdinc++ -I/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3/include/ee -I/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3/include -I../../../../libstdc++-v3/libsupc++ -I../../../../libstdc++-v3/libmath -g -O2 -fno-implicit-templates -Wall -Wno-format -W -Wwrite-strings -Winline -fdiagnostics-show-location=once -G0 -g -c ../../../../libstdc++-v3/src/ios.cc -o ios.o
make[3]: Leaving directory '/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3/src'
Makefile:274: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3'
Makefile:405: recipe for target 'all-recursive-am' failed
make[1]: *** [all-recursive-am] Error 2
make[1]: Leaving directory '/root/ps2toolchain/build/gcc-3.2.3/build-ee-stage2/ee/libstdc++-v3'
Makefile:1514: recipe for target 'all-target-libstdc++-v3' failed
make: *** [all-target-libstdc++-v3] Error 2
../scripts/004-gcc-3.2.3-stage2.sh: Failed.`

**Comment by sp193** [comment]
The script attempts to get the number of processors from $(nproc), but not all operating systems have that included. MinGW does not, which is why there is an exception for it.
If you can work with scripts, can you verify that [```$PROC_NR```](https://github.com/ps2dev/ps2toolchain/blob/master/scripts/004-gcc-3.2.3-stage2.sh#L34) gets set to a sane value? If not, then we might need to figure out how to set this variable properly under the Windows Linux subsystem.

I'm not sure what the error means, however. :(

If all else fails, can you verify that removing the [```-j $PROC_NR```](https://github.com/ps2dev/ps2toolchain/blob/master/scripts/004-gcc-3.2.3-stage2.sh#L47) option helps?

**Comment by AKuHAK** [comment]
> If all else fails, can you verify that removing the [`-j $PROC_NR`](https://github.com/ps2dev/ps2toolchain/blob/master/scripts/004-gcc-3.2.3-stage2.sh#L47) option helps?

Yes, commenting whole section (as it was done in other scripts) helps - this was first I tried. I will try to figure out what's wrong with $PROC_NR

**Comment by AKuHAK** [comment]
I was trying to reproduce the issue - but failed. 004 script compiles 3 times just fine, maybe this error happens in some very rare cases when there are some overload in multiple flows.

**Comment by sp193** [comment]
Can you write a script like this, to see if the number of cores is printed correctly?

```
#!/bin/sh
echo $(nproc)
```

And if it does not, then what about this?
```
#!/bin/sh
echo $NUMBER_OF_PROCESSORS
```

We also need to know how to identify the OS, in case we need special handling:
```
#!/bin/sh
echo $OSVER
```

**Comment by AKuHAK** [comment]
ps2toolchain scripts are correct - all 4 cores are shown. OS Version are correctly identified too (linux).

I compiled 10 times with no error :( I think that there is really something wrong in very rare cases and this is not dependent on OS version. I noticed that sometimes some my travis build failed cause of similar error.

**Comment by AKuHAK** [comment]
After switching EE side to the gcc >= 5 problems disappears.
