### ISSUE TITLE
question about the targets of stage 1 and stage 2 gcc build

### ISSUE THREAD

**Issue by sl1pkn07** [ps2dev/ps2toolchain#52]
Hi

i have a one question about the stage1 and stage2 gcc build steps

why the stage1 have as target `ee` and `iop` and the stage 2 only have `ee`?

https://github.com/ps2dev/ps2toolchain/blob/master/scripts/002-gcc-3.2.3-stage1.sh#L40
https://github.com/ps2dev/ps2toolchain/blob/master/scripts/004-gcc-3.2.3-stage2.sh#L39

also, stage1 enable only `c` language and stage2 enables `c` and `c++`

if i build the toolchain separately without use the main build scripts (but patching the sources adequately), i can build the stage2 with `ee` and `iop` targets?

i say this because i install the toolchain separately in their own package (one for binutils, other for stage1 gcc, other for newlib, other for stage2 gcc, other for ps2sdk, etc etc) but when install the stage2 i need remove the stage1 gcc for avoid file conflicts when install the package (same file include in the both packages)

greetings

**Comment by sp193** [comment]
We need to build GCC first, before Newlib can be built, before we can build GCC with support for Newlib. We use Newlib exclusively for C++, while the ps2sdk's libc is used for C. It may be possible to just use Newlib.

We do not support C++ for the IOP, as it is not a target with a lot of resources. So there is not much point in using C++ there.

**Comment by sl1pkn07** [comment]
but i can build with it?

> Necesitamos crear GCC primero, antes de poder construir Newlib, antes de poder construir GCC con soporte para Newlib. 

yep, i doing this, is like my distro doing (https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gcc#n4) , no problem here

>Utilizamos Newlib exclusivamente para C ++, mientras que la libc de ps2sdk se usa para C. Es posible que solo se use Newlib.
> 
> No admitimos C ++ para el IOP, ya que no es un objetivo con muchos recursos. Así que no tiene mucho sentido usar C ++ allí.

but i can build it? even though is not used

greetings

**Comment by fjtrujy** [comment]
Hi @sl1pkn07 !
You have put some spanish translation, I think that @sp193 doesn't know Spanish xD, please edit the previous message.
Interesting topic by the way
Thanks!

**Comment by sl1pkn07** [comment]
ops!

**Comment by sp193** [comment]
I doubt it will compile because it will not recognize the "iop" target. For Newlib to support a new target, it has to be customized for the target.

In the case of the IOP, we use the Sony libraries. So the C compiler does not come with any libraries, other than libgcc, which contains some additional functions for GCC that are implemented in software.
