### ISSUE TITLE
../depends/check-ps2dev.sh: Failed.

### ISSUE THREAD

**Issue by jpc0016** [ps2dev/ps2toolchain#55]
While attempting to install the toolchain, I received a previously closed error.  There was no remedy or follow-up explained.  I have all dependencies in step 1 and appended all export statements to my `~/.bashrc` file.

```
ERROR: Set $PS2DEV before continuing.
../depends/check-ps2dev.sh: Failed.
```

Something strange is happening where `toolchain.sh` is not recognizing the new imports.  I even explicitly imported the paths in the command line.  Please advise.

**Comment by sp193** [comment]
You need to set this environment variable. If you added it to your .bashrc file, then have you logged off and back on? Did you execute the script with your own user account, or did you execute it as root?

The .bashrc file is only applicable to your own account. So if you do run the script as root, then it would not help.

**Comment by uyjulian** [comment]
You may need to add the setting to the `~/.bash_profile` file.

If you elevate permissions from your user account via `sudo`, there is no need to add the variables to the root account's `~/.bash_profile` file.

Make sure to evaluate the contents in `~/.bash_profile` in the current context before attempting to run the toolchain.

**Comment by fjtrujy** [comment]
Hello,
Closing this issue because it was quite clear that the user didn't define the bash environment properly.

Thanks
