### ISSUE TITLE
script 005 fails with syntax errors in include/ps2sdkapi.h

### ISSUE THREAD

**Issue by penguin2233** [ps2dev/ps2toolchain#63]
`include/ps2sdkapi.h:31: syntax error before '*' token
cc1: warnings being treated as errors
include/ps2sdkapi.h:31: warning: type defaults to `int' in declaration of `_ps2sdk_opendir'
include/ps2sdkapi.h:31: warning: data definition has no type or storage class
include/ps2sdkapi.h:32: syntax error before '*' token
include/ps2sdkapi.h:33: syntax error before '*' token
include/ps2sdkapi.h:34: syntax error before '*' token
Reaping losing child 0x7fffce2ec610 PID 19044
make[2]: *** [/mnt/y/PS2Dev/ps2toolchain/scripts/ps2sdk/ee/Rules.make:54: obj/sleep.o] Error 1
Removing child 0x7fffce2ec610 PID 19044 from chain.
make[2]: Leaving directory '/mnt/y/PS2Dev/ps2toolchain/scripts/ps2sdk/ee/libc'
Reaping losing child 0x7fffbf362180 PID 19040
make[1]: *** [/mnt/y/PS2Dev/ps2toolchain/scripts/ps2sdk/Rules.make:21: all-libc] Error 2
Removing child 0x7fffbf362180 PID 19040 from chain.
make[1]: Leaving directory '/mnt/y/PS2Dev/ps2toolchain/scripts/ps2sdk/ee'
Reaping losing child 0x7fffe4ab7f30 PID 17231
make: *** [Makefile:31: all-ee] Error 2
Removing child 0x7fffe4ab7f30 PID 17231 from chain.`

this is output from make using -d flag
I already downgraded newlib to 1.10 so script 3 would work (if that had anything to do with this error)

**Comment by rickgaiser** [comment]
You cannot downgrade newlib alone. Please build the standard/unchanged sources. If there's any issues in building those then we can help.

It's possible you're missing the texinfo package. Try installing that first.

**Comment by penguin2233** [comment]
installing texinfo package worked, thank you

**Comment by Jay-Jay-OPL** [comment]
@penguin2233, just curious?  What platform are you using to compile this?  i.e. Windows, Linux, VirtualBox, or other?

**Comment by penguin2233** [comment]
Debian Buster on WSL
