### ISSUE TITLE
`makeinfo' is missing on your system.

### ISSUE THREAD

**Issue by rickgaiser** [ps2dev/ps2toolchain#64]
Newlib 1.14 depends on makeinfo / texinfo. When not installed this will give an error like:
```
WARNING: `makeinfo' is missing on your system.  You should only need it if
         you modified a `.texi' or `.texinfo' file, or any other file
         indirectly affecting the aspect of the manual.  The spurious
         call might also be the consequence of using a buggy `make' (AIX,
         DU, IRIX).  You might want to install the `Texinfo' package or
         the `GNU make' package.  Grab either from any GNU archive site.
make[3]: *** [standards.info] Error 1
make[2]: *** [info] Error 1
make[1]: *** [all-etc] Error 2
```

I'm placing this issue here since there seems to be a lot of developers having this issue. On Linux/Ubuntu this can be solved with:
`sudo apt install texinfo`

**Comment by fjtrujy** [comment]
We should update the readme with the needed dependencies.

I will do in the same PR where I'm working into the integration of `GitHub Actions`

**Comment by fjtrujy** [comment]
Hello @rickgaiser,
As soon as this https://github.com/ps2dev/ps2toolchain/pulls get merged, we can close this issue.

Thanks!

**Comment by fjtrujy** [comment]
This ticket can be now closed.
Thanks
