### ISSUE TITLE
Installation script fails

### ISSUE THREAD

**Issue by SignalSpectre** [ps2dev/ps2toolchain#72]
I'm trying to install the toolchain on Windows Subsystem for Linux but I get these errors:

`libtool: link: only absolute run-paths are allowed`
`make[3]: *** [Makefile:928: libbfd.la] Error 1`
`make[2]: *** [Makefile:942: all-recursive] Error 1`
`make[1]: *** [Makefile:1088: all-recursive-am] Error 2`
`make: *** [Makefile:1644: all-bfd] Error 2`
`../scripts/001-binutils-2.14.sh: Failed.`

I really don't know how I can fix these (I tried searching the correct makefile but failed miserably…).
This happen to me every time even on different computers with a fresh installation of WSL: how can I solve it?

**Comment by AKuHAK** [comment]
try
`sudo apt-get -y install texinfo bison flex`
If this solves your problem probably this dependencies should be checked before.

**Comment by SignalSpectre** [comment]
Thanks for helping me.
I tried to install bison and flex (texinfo was already installed) but sadly nothing changed: I get the same errors as before (I have some less warning tough).
Could it be that I'm missing some other dependecies?

**Comment by Jay-Jay-OPL** [comment]
Just wondering?  In case it makes a difference, what versions (`? --version`) of these dependencies should we make sure we have?

**Comment by AKuHAK** [comment]
@SignalSpectre it seems that you have some spaces or special characters in some path. This can be your PATH, (for example your username), PS2DEV, or something similar. Please ensure that your Windows username contains only Latin chars without spaces, and that you didn't change PS2DEV path into something with spaces or non-Latin chars.

**Comment by SignalSpectre** [comment]
Both my Windows and WSL usernames are using only latin characters with no spaces and so is the PS2DEV path.
In the end I managed to install the toolchain (as well as the other components of the development environment) using the ps2dev script as root, could it be a permission problem? (I know it doesn't seem to be so but I'm sure I don't have spaces or non latin characters in both the PS2DEV path and the username).

**Comment by AKuHAK** [comment]
@SignalSpectre It looks like permission problem, I just thought that you already tried to install it as root. I added a possible solution for this problem into [Readme](https://github.com/ps2dev/ps2toolchain#requirements):
```bash
export PS2DEV=/usr/local/ps2dev
sudo mkdir -p $PS2DEV
sudo chown -R $USER: $PS2DEV
```
It is also possible that `git clone` was made with root privileges, or any middle command by accident was made with root. In such cases, it is very difficult to track down where is "root". If you wish you can completely reinstall PS2DEV with user privileges with the provided solution.

**Comment by AKuHAK** [comment]
@rickgaiser @fjtrujy @SignalSpectre this issue can be closed - it was produced due to a permission denied problem which now is covered in [Readme](https://github.com/ps2dev/ps2toolchain#requirements).

**Comment by rickgaiser** [comment]
Thank you for following up on this @AKuHAK
