### ISSUE TITLE
not building in cygwin (fixed manually by editing files mid-build)

### ISSUE THREAD

**Issue by skompc** [ps2dev/ps2toolchain#77]
Problem is as title says

I fixed it by changing all mentions of "MINGW64_NT" to "CYGWIN_NT-" and all mentions of "MINGW" to "CYGWI" in all files from the scripts folder then running toolchain.sh once.
Then I commented out lines 6,7,10,11,15, and 16 from 001-binutils.sh
Next I changed line 188 in build/binutils-2.14/libierty/pexwin-32.c to remove the underscores from before "spawnvp" and "spawnv"
Finally I ran toolchain.sh again

still running build and will edit when complete and tested

**Comment by AKuHAK** [comment]
@skompc do you have any luck with your build?

**Comment by skompc** [comment]
> @skompc do you have any luck with your build?

Unfortunately not... I haven't found the exact issue yet but I decided to reinstall windows for other reasons so I'll probably do it again using a fresh build environment

**Comment by uyjulian** [comment]
This doesn't seem to be an issue anymore. Reopen if this is not the case
