### ISSUE TITLE
Why very old binutils, gcc and newlib?

### ISSUE THREAD

**Issue by terremoth** [ps2dev/ps2toolchain#78]
It does not work with new versions of it?

**Comment by fjtrujy** [comment]
Exactly. The 3 items, gcc, binutils and newlib they have a specific patch with the needed changes to make it work for the PS2. Upgrade them to a newer version is not an easy task and requires a lot of time and knowledge.

**Comment by terremoth** [comment]
@fjtrujy ah. okay :cry:   
maybe one day we could achieve that

**Comment by terremoth** [comment]
Will this be an active issue for people interested in port those tools to new versions, or can I close this issue?

**Comment by uyjulian** [comment]
They have been updated now for EE. This issue can be closed

**Comment by fjtrujy** [comment]
Closing issue.

**Comment by terremoth** [comment]
Wow.
Wait, so *everything*  was updated to new GCC version (10) or some things would still using the old one? 
@fjtrujy @uyjulian

**Comment by uyjulian** [comment]
Only EE was updated.

**Comment by terremoth** [comment]
@uyjulian that is a great and excellent progress already. Nice!
