### ISSUE TITLE
Building ps2toolchain on Windows (using mingw)

### ISSUE THREAD

**Issue by madebr** [ps2dev/ps2toolchain#81]
Hello,

I've created [a conan recipe for building ps2toolchain](https://github.com/madebr/conan-ps2dev).
This is a transliteration of the bash scripts to a python conan script, using the ps2dev patches.
It is currently [able to create packages for Linux and Macos](https://github.com/madebr/conan-ps2dev/actions/runs/402006877).

Creating packages on Windows (using [this mingw toolchain](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/)) fails while building binutils (more specific the intl library).
[This is the build log.](https://github.com/madebr/conan-ps2dev/runs/1502444679?check_suite_focus=true)
This error is shown:
```
 make[1]: /c/users/runneradmin/.conan/data/mingw_installer/1.0/conan/stable/package/4b8f5a096ecfd6aabff608521169f167b01837ec/bin/gcc.exe: Bad address
```
Does this error ring a bell somewhere?
Is it actually possible to build ps2toolchain on Windows using mingw?
The same error is emitted when using the bash scripts.

This mingw toolchain is used:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/

NB: I had to apply 2 changes to get it building on apple-clang:
- add `-DSTDC_HEADERS` to `CFLAGS` while building binutils and gcc
- Applied this patch on newlib:
   ```patch
   --- newlib/doc/makedoc.c
   +++ newlib/doc/makedoc.c
   @@ -42,2 +42,2 @@
   -extern PTR malloc();
   -extern PTR realloc();
   +#include <stdlib.h>
   +#include <string.h>
   ```

Thanks!

**Comment by fjtrujy** [comment]
Hello @madebr.
I'm not sure if it currently compiles on Windows using `mingw`, we are sure that it compiles in `WSL`.

Anyway, now we have split the toolchain into smaller parts and repos. So first of all, I think that this issue, "if it still exists", should be moved to the  https://github.com/ps2dev/ps2toolchain-ee
Have in mind that the whole toolchain has been updated, so most probably even these specific changes are no longer valid anyway.

So please, don't hesitate to create the issue there.

Thanks!
