### ISSUE TITLE
.libs/libc++17convenience.a: malformed archive

### ISSUE THREAD

**Issue by protoman** [ps2dev/ps2toolchain#93]
System: Linux Mint 20.3 x64 on Ryzen 56000G.
Trying to build the PS2DEV

libtool: compile:  /media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/./gcc/xgcc -shared-libgcc -B/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/./gcc -nostdinc++ -L/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/mips64r5900el-ps2-elf/libstdc++-v3/src -L/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/mips64r5900el-ps2-elf/libstdc++-v3/src/.libs -L/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/mips64r5900el-ps2-elf/libstdc++-v3/libsupc++/.libs -B/media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/bin/ -B/media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/lib/ -isystem /media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/include -isystem /media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/sys-include -I/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/libstdc++-v3/../libgcc -I/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/mips64r5900el-ps2-elf/libstdc++-v3/include/mips64r5900el-ps2-elf -I/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/build-mips64r5900el-ps2-elf-stage2/mips64r5900el-ps2-elf/libstdc++-v3/include -I/media/iuri/SamsungEXT4/development/SDK/PS2/ps2dev/build/ps2toolchain/build/ps2toolchain-ee/build/gcc/libstdc++-v3/libsupc++ -std=gnu++17 -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi=2 -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=cow-fs_ops.lo -fimplicit-templates -g -O2 -G0 -c ../../../../../libstdc++-v3/src/c++17/cow-fs_ops.cc -o cow-fs_ops.o
libtool: link: /media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/bin/ar rc .libs/libc++17convenience.a  floating_from_chars.o floating_to_chars.o fs_dir.o fs_ops.o fs_path.o memory_resource.o cow-fs_dir.o cow-fs_ops.o cow-fs_path.o ostream-inst.o string-inst.o cow-string-inst.o
libtool: link: /media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/bin/ranlib .libs/libc++17convenience.a
/media/iuri/SamsungEXT4/development/SDK/PS2/sdk/ee/mips64r5900el-ps2-elf/bin/ranlib: .libs/libc++17convenience.a: malformed archive

**Comment by protoman** [comment]
After a second run, without any modifications, it worked. So there is this workaround, but I'll leave the bug open until I get some information about it.

**Comment by uyjulian** [comment]
Either corruption or concurrency issue.

This doesn't seem to be an issue anymore. Reopen if this is not the case
