### ISSUE TITLE
Help with compiling please.

### ISSUE THREAD

**Issue by PS-2Online** [ps2dev/ps2toolchain#96]
First, can somone give me the exact syntax and commands I need to use to compile my makefile? I am trying to compile from basic samples. I am new to this side of programming. I only have problems with compiling, I just know I am not doing something right.

Second, whenever I make my makefile, it exports two files, hello.o and libkernel.erl. I put libkernel.erl into ps2packer and compressed to .elf but the file is bad and will not work on PS2 (obviously). Also, when I do compile, I get:

![1659275277483112305765](https://user-images.githubusercontent.com/110340463/182029454-8af3cf6a-ef37-4720-9018-368224651a1f.jpg)

If anyone could help that'd be great. Could be bad installation, I did have problem with the $PS2DEV thing but it seems to resolve just fine up to this point. Saw some errors during install. Maybe something is missing? Anyway, your help would be great, I really would like to make some utilities for PS2. Thanks and God bless.

**Comment by PS-2Online** [comment]
I am using Ubuntu by the way.

**Comment by AKuHAK** [comment]
Erl support is broken.

**Comment by PS-2Online** [comment]
Is there a way to fix this?

**Comment by PS-2Online** [comment]
Upon further inspection multiple compilers are looking for erl.h. I sewrched for it and it exists. It is located at usr/local/ps2dev/ps2sdk/ee/include. Is there somewhere else it needs to be?

**Comment by uyjulian** [comment]
ERL is not fully supported at this time.

The other non-ERL and non-MPEG samples should continue to work just fine.

**Comment by PS-2Online** [comment]
How do I compile without erl?

**Comment by uyjulian** [comment]
Use the other sample.

**Comment by PS-2Online** [comment]
I think erl was included by mistake. I took it was a vital system function. My applogies. :P

**Comment by PS-2Online** [comment]
Last question. I run make on a different sample and it compiles well but what do I do with .elf and .o files? I used ps2packer on elf but it did not run. Is there a step I am missing here?

**Comment by fjtrujy** [comment]
The elf file is the executable that you can run in your PS2 through wLaunch or whatever launcher you have installed in your PS2.
You can also use PCSX2 emulator it is faster and easier.

**Comment by PS-2Online** [comment]
Strange, when I run the elf it does not work on the ps2.

I'm simply using make on a sample.

**Comment by fjtrujy** [comment]
Try first with PCSX2. 
Have in mind that some samples are trying to load some files. If the files aren’t present it won’t work

**Comment by PS-2Online** [comment]
I tremendously suck indeed. Ran elf blank screen but new twist: PS2 statted getting hot. I have to be doing something wrong

**Comment by PS-2Online** [comment]
Oh

**Comment by PS-2Online** [comment]
Ok the solution has been revealed to me. I realize that the printf does not print text on the screen like a console. Im guessing I failed to implement something but my elf compilation is working fine, just won't shos text. Thanks for your help everyone, God bless you all!

**Comment by terremoth** [comment]
Classic problem this -mno-crt0...
The ps2sdk hello world is (at least was until some months ago) broken.

I tried and had the same error. Some guys in the ps2-scene discord told me it was broken the way it is in this repo. 
So I made 2 hello worlds that were fixed/done correctly, one hello world in the screen and another in the console (pcsx2): https://github.com/terremoth/ps2-examples

@PS-2Online take a look at the ps2_screen folder, including the Makefile, so you can understand a little bit.

**Comment by PS-2Online** [comment]
I found  a sample tucked away in a folder that I would not look into because it seemed like nothing would be there and I found a debug console program. It is really grainy text though! I may look into your programs in the future if it looks better or is more customizable. I just need some basic screen output to see what I am doing.

**Comment by PS-2Online** [comment]
)
