### ISSUE TITLE
Distro packaging (AUR, nix)

### ISSUE THREAD

**Issue by tallero** [ps2dev/ps2toolchain#99]
Hello, I've packaged the toolchain as a set of AUR packages.

Would you agree this the correct package structure?

- [`ps2-sdk`](https://aur.archlinux.org/packages/ps2-sdk):
  - [`ps2-toolchain`](https://aur.archlinux.org/packages/ps2-toolchain):
    - [`ps2-dvp`](https://aur.archlinux.org/packages/ps2-dvp)
      - [`dvp-binutils`](https://aur.archlinux.org/packages/dvp-binutils)
    - [`ps2-iop`](https://aur.archlinux.org/packages/ps2-iop)
      - [`mipsel-ps2-irx-binutils`](https://aur.archlinux.org/packages/mipsel-ps2-irx-binutils)
      - [`mipsel-ps2-irx-gcc-stage1`](https://aur.archlinux.org/packages/mipsel-ps2-irx-gcc-stage1) (can I drop `stage1` here?)
      - [`mipsel-ps2-elf-binutils`](https://aur.archlinux.org/packages/mipsel-ps2-elf-binutils)
      - [`mipsel-ps2-elf-gcc-stage1`](https://aur.archlinux.org/packages/mipsel-ps2-irx-gcc-stage1) (can I drop `stage1` here?)
    - [`ps2-ee`](https://aur.archlinux.org/packages/ps2-ee)
      - [`mips64r5900el-elf-binutils`](https://aur.archlinux.org/packages/mips64r5900el-elf-binutils)
      - [`mips64r5900el-elf-gcc-stage1`](https://aur.archlinux.org/packages/mips64r5900el-elf-gcc-stage1)
      - [`mips64r5900el-elf-newlib`](https://aur.archlinux.org/packages/mips64r5900el-elf-newlib)
      - [`mips64r5900el-elf-newlib-nano`](https://aur.archlinux.org/packages/mips64r5900el-elf-newlib-nano)
      - [`mips64r5900el-pthread-embedded`](https://aur.archlinux.org/packages/mips64r5900el-pthread-embedded)
      - [`mips64r5900el-elf-gcc`](https://aur.archlinux.org/packages/mips64r5900el-elf-gcc)

**Comment by 6e6f61** [comment]
Input on this would be appreciated. I'm trying to package ps2toolchain with Nix.

**Comment by uyjulian** [comment]
You can package things however you want. But stuff may break if you don't do stuff that `ps2dev/ps2dev` repository will do it

**Comment by tallero** [comment]
I'm okay with Archlinux packaging of the SDK by far, I'm trying to get an old `cdvd` source now.

**Comment by uyjulian** [comment]
This doesn't seem to be an issue anymore. Reopen if this is not the case
